![Imgur](https://i.imgur.com/h4PPC71.png)
#Data Sayns va Sunʼiy Intellekt Praktikum

#8.26. NumPy kutubxonasi boʻyicha amaliy vazifa

Topshiriqni aynan qanday funksiyalar yordamida bajarish mumkinligi `💡Ishora` koʻrinishida berilgan.

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va uni chop eting.

Versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [3]:
import numpy as np
print("NumPy versiyasi:", np.__version__)
print("\nKonfiguratsiya tafsilotlari:")
np.show_config()

NumPy versiyasi: 2.0.2

Konfiguratsiya tafsilotlari:
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  

#### 2. Raqamli qiymatlar roʻyxatini bir oʻlchovli NumPy massiviga aylantiring.

`💡Ishora` numpy.array

In [4]:
python_royxat = [10, 20, 30, 40, 50]
numpy_massiv = np.array(python_royxat)
print("NumPy massivi:", numpy_massiv)
print("Turi (type):", type(numpy_massiv))

NumPy massivi: [10 20 30 40 50]
Turi (type): <class 'numpy.ndarray'>


#### 3. Qiymatlari noldan iborat boʻlgan toʻqqiz elementdan iborat massiv yarating.


---




`💡Ishora` np.zeros

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [5]:
massiv = np.arange(10)
elementlar_soni = massiv.size
element_hajmi = massiv.itemsize
jami_hajm = elementlar_soni * element_hajmi
print(f"Elementlar soni: {elementlar_soni}")
print(f"Bitta element hajmi: {element_hajmi} bayt")
print(f"Massivning jami xotira hajmi: {jami_hajm} bayt")

Elementlar soni: 10
Bitta element hajmi: 8 bayt
Massivning jami xotira hajmi: 80 bayt


#### 5. NumPy kutubxonasidagi `add` funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Shunday vekor yaratingki u oʻn ikki oʻlchamda va qiymatlari noldan iborat boʻlsin, lekin vektorning oltinchi qiymati 1 ga teng boʻlsin.



`💡Ishora` array[12]

In [7]:
vektor = np.zeros(12)
vektor[5] = 1
print(vektor)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


#### 7. Qiymatlari 20 dan 59 gacha boʻlgan vektor yarating.



`💡Ishora` arange

In [8]:
vektor = np.arange(20, 60)

print(vektor)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]


#### 8. Vektor yarating va uni teskari oʻzgartiring, (birinchi element oxirgisi boʻlsin)



`💡Ishora` array[::-1]

In [9]:
vektor = np.arange(10)
print("Asl vektor:", vektor)
teskari_vektor = vektor[::-1]
print("Teskari vektor:", teskari_vektor)

Asl vektor: [0 1 2 3 4 5 6 7 8 9]
Teskari vektor: [9 8 7 6 5 4 3 2 1 0]


#### 9. 12 dan 20 gacha boʻlgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [10]:
vektor = np.arange(12, 21)
matritsa = vektor.reshape(3, 3)

print(matritsa)

[[12 13 14]
 [15 16 17]
 [18 19 20]]


#### 10. Quyidagi matritsadan foydalanib nolga teng boʻlmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [11]:
massiv = np.array([3, 7, 0, 0, 9, 0])
indekslar = np.nonzero(massiv)

print("Nolga teng bo'lmagan elementlar indekslari:", indekslar)

Nolga teng bo'lmagan elementlar indekslari: (array([0, 1, 4]),)


#### 11. Tasodifiy qiymatlar bilan 2x2x2 oʻlchovidagi massiv yarating.


`💡Ishora` np.random.random

In [12]:
tasodifiy_massiv = np.random.random((2, 2, 2))

print(tasodifiy_massiv)

[[[0.97595176 0.74322371]
  [0.21646672 0.24174522]]

 [[0.92612514 0.17681071]
  [0.19705044 0.9385969 ]]]


#### 12. Tasodifiy sonlardan tashkil topgan 9X9 oʻlchamidagi massiv yarating. Soʻng uning eng katta va eng kichik qiymatlarini toping.


`💡Ishora` min, max

In [13]:
massiv = np.random.random((9, 9))
minimal = massiv.min()
maksimal = massiv.max()

print(f"Eng kichik qiymat: {minimal}")
print(f"Eng katta qiymat: {maksimal}")

Eng kichik qiymat: 0.010158792569269992
Eng katta qiymat: 0.9999784040190051


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [17]:
np.nan
False
False
np.nan
True
False

False

#### 14. Oʻlchamlari 6x3 va 3x4 boʻlgan martitsa yarating, soʻng ularning  koʻpaytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [18]:
matritsa1 = np.ones((6, 3))
matritsa2 = np.random.random((3, 4))
natija = np.dot(matritsa1, matritsa2)

print("Natijaviy matritsa o'lchami:", natija.shape)
print(natija)

Natijaviy matritsa o'lchami: (6, 4)
[[1.25761521 1.60812814 1.9573732  1.02794926]
 [1.25761521 1.60812814 1.9573732  1.02794926]
 [1.25761521 1.60812814 1.9573732  1.02794926]
 [1.25761521 1.60812814 1.9573732  1.02794926]
 [1.25761521 1.60812814 1.9573732  1.02794926]
 [1.25761521 1.60812814 1.9573732  1.02794926]]


#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [19]:
9
10

10

#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [20]:
a = np.array([1, 2])
b = np.array([4, 5])

# Solishtirish amallarini bajaramiz
print("a > b  :", a > b)
print("a >= b :", a >= b)
print("a < b  :", a < b)
print("a <= b :", a <= b)

a > b  : [False False]
a >= b : [False False]
a < b  : [ True  True]
a <= b : [ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [21]:
np.nan
0
-9.223372036854776e+18

-9.223372036854776e+18

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping.


`💡Ishora` np.intersect1d

In [22]:
massiv1 = np.array([10, 20, 30, 40, 50])
massiv2 = np.array([30, 40, 50, 60, 70])
umumiy_qiymatlar = np.intersect1d(massiv1, massiv2)

print("Birinchi massiv:", massiv1)
print("Ikkinchi massiv:", massiv2)
print("Umumiy qiymatlar:", umumiy_qiymatlar)

Birinchi massiv: [10 20 30 40 50]
Ikkinchi massiv: [30 40 50 60 70]
Umumiy qiymatlar: [30 40 50]


#### 19. Tasodifiy sonlardan iborat boʻlgan massiv yarating, soʻng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` % (Sonning kasr qismi - qoldiq), np.floor, astype, np.trunc

In [23]:
# 1. Tasodifiy o'nlik sonlardan iborat massiv yaratamiz
x = np.random.uniform(-10, 10, 5)
print("Asl massiv:", x)

# Usul 1: % (Qoldiq olish operatori yordamida ayirish)
res1 = x - x % 1

# Usul 2: np.floor (Har doim pastga qarab yaxlitlash)
res2 = np.floor(x)

# Usul 3: astype(int) (Ma'lumot turini butun songa o'zgartirish)
res3 = x.astype(int)

# Usul 4: np.trunc (Kasr qismini shunchaki kesib tashlash)
res4 = np.trunc(x)

print("1-usul (%):", res1)
print("2-usul (floor):", res2)
print("3-usul (astype):", res3)
print("4-usul (trunc):", res4)

Asl massiv: [-8.56173314 -4.17636988 -3.3693221   5.0347545  -3.40314217]
1-usul (%): [-9. -5. -4.  5. -4.]
2-usul (floor): [-9. -5. -4.  5. -4.]
3-usul (astype): [-8 -4 -3  5 -3]
4-usul (trunc): [-8. -4. -3.  5. -3.]


#### 20. Oʻlchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha boʻlsin.



`💡Ishora` np.arange

In [24]:
matritsa = np.zeros((3, 3))
matritsa = matritsa + np.arange(3)

print(matritsa)

[[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]


#### 21. Oʻchamlari 10 boʻlgan tasodifiy vektor yarating va uni oʻsish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [25]:
vektor = np.random.random(10)
print("Tartiblanmagan vektor:\n", vektor)
vektor.sort()

print("\nO'sish tartibida saralangan vektor:\n", vektor)

Tartiblanmagan vektor:
 [0.60559941 0.71710538 0.78939388 0.41086544 0.07676827 0.60207635
 0.69825901 0.76311856 0.12201302 0.88978511]

O'sish tartibida saralangan vektor:
 [0.07676827 0.12201302 0.41086544 0.60207635 0.60559941 0.69825901
 0.71710538 0.76311856 0.78939388 0.88978511]


#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring.

`💡Ishora` np.allclose, np.array_equal

In [26]:
A = np.random.random(5)
B = np.random.random(5)

# 1. Birinchi usul: np.array_equal
# Bu usul massivlar o'lchami va elementlari aynan (100%) bir xil bo'lishini tekshiradi
tengmi_mutloq = np.array_equal(A, B)

# 2. Ikkinchi usul: np.allclose
# Bu usul elementlar orasidagi juda kichik farqni (aniqlik xatosini) hisobga oladi
# Tasodifiy o'nlik sonlar uchun ko'pincha shu usul ishlatiladi
tengmi_yaqin = np.allclose(A, B)

print(f"A massiv: {A}")
print(f"B massiv: {B}")
print(f"Mutloq tengmi? {tengmi_mutloq}")
print(f"Yaqinlik darajasi bo'yicha tengmi? {tengmi_yaqin}")

A massiv: [0.60251188 0.94470972 0.06587319 0.77143452 0.16931558]
B massiv: [0.19993704 0.97975439 0.26043151 0.40049311 0.72028897]
Mutloq tengmi? False
Yaqinlik darajasi bo'yicha tengmi? False


#### 23. 5 dan 15 gacha bo'lgan sonlardan iborat massiv yarating. Massivdagi 10 dan katta elementlarni ajratib oling va ularning yig‘indisini hisoblang.


`💡Ishora` sum()

In [28]:
massiv = np.arange(5, 16)
print("Asl massiv:", massiv)

katta_10 = massiv[massiv > 10]
print("10 dan katta elementlar:", katta_10)
yigindi = katta_10.sum()
print("Yig'indi:", yigindi)

Asl massiv: [ 5  6  7  8  9 10 11 12 13 14 15]
10 dan katta elementlar: [11 12 13 14 15]
Yig'indi: 65


#### 24. Tasodifiy sonlardan iborat boʻlgan oʻlchami 5 ga teng vektor yarating, soʻng uning eng katta qiymatini 0 ga oʻzgartiring.


`💡Ishora` argmax

In [29]:
vektor = np.random.random(5)
print("Asl vektor:", vektor)
maks_indeks = vektor.argmax()
vektor[maks_indeks] = 0

print("O'zgartirilgan vektor:", vektor)

Asl vektor: [0.71478509 0.19618426 0.75621841 0.8708522  0.25576831]
O'zgartirilgan vektor: [0.71478509 0.19618426 0.75621841 0.         0.25576831]


#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [30]:
bugun = np.datetime64('today', 'D')
kecha = bugun - np.timedelta64(1, 'D')
ertaga = bugun + np.timedelta64(1, 'D')

print("Kecha: ", kecha)
print("Bugun: ", bugun)
print("Ertaga:", ertaga)

Kecha:  2026-03-13
Bugun:  2026-03-14
Ertaga: 2026-03-15


#### 26. 2016 yil yanvar oyiga toʻgʻri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [31]:
sanalar = np.arange('2016-01', '2016-02', dtype='datetime64[D]')

print(sanalar)

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 2.6, 7.9, 9.8, 4.2 elementlardan tashkil topgan arr yarating va uni arr1 deb nomlang. Keyin massivdagi har bir sonning butun qismini oling va yangi massiv - arr2 ni hosil qiling.


`💡Ishora` astype(int)

In [32]:
arr1 = np.array([2.6, 7.9, 9.8, 4.2])
arr2 = arr1.astype(int)

print("Asl massiv (arr1):", arr1)
print("Butun qismli massiv (arr2):", arr2)

Asl massiv (arr1): [2.6 7.9 9.8 4.2]
Butun qismli massiv (arr2): [2 7 9 4]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yigʻindisini `np.sum` funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [33]:
massiv = np.random.random(100)
tezkor_yigindi = np.add.reduce(massiv)

print("Massiv yig'indisi:", tezkor_yigindi)

Massiv yig'indisi: 52.496647625199635


#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [34]:
asl_vektor = np.array([1, 2, 3, 4, 5])

n_nol = 3
yangi_uzunlik = len(asl_vektor) + (len(asl_vektor) - 1) * n_nol
yangi_vektor = np.zeros(yangi_uzunlik, dtype=int)
yangi_vektor[::n_nol + 1] = asl_vektor

print(yangi_vektor)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 30. Quyidagi `a` massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda `b` massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

`💡Ishora` stride_tricks.as_strided

In [35]:
from numpy.lib import stride_tricks

# 1. Asl massivni yaratamiz
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

# 2. Parametrlarni aniqlaymiz
oyna_uzunligi = 4
qatorlar_soni = len(a) - oyna_uzunligi + 1
qadam_bayti = a.strides[0] # Har bir element xotirada necha bayt egallashi

# 3. as_strided yordamida b massivini hosil qilamiz
b = stride_tricks.as_strided(
    a,
    shape=(qatorlar_soni, oyna_uzunligi),
    strides=(qadam_bayti, qadam_bayti)
)

print(b)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga oʻxshash qiymatlar kiriting. Soʻng, oʻxshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [36]:
a = np.array([1, 3, 2, 8, 3, 1, 3, 4, 1, 3])
counts = np.bincount(a)
eng_kop_takrorlangan = np.argmax(counts)

print("Massiv:", a)
print("Eng ko'p takrorlangan (o'xshash) qiymat:", eng_kop_takrorlangan)
print(f"U {counts[eng_kop_takrorlangan]} marta takrorlangan.")

Massiv: [1 3 2 8 3 1 3 4 1 3]
Eng ko'p takrorlangan (o'xshash) qiymat: 3
U 4 marta takrorlangan.


#### BONUS topshiriq

`💡Oʻzingiz javob berishni istagan savolni kiriting va unga javob bering.`